### ISSUE TITLE
Topics to be covered during the 2023 tutorial

### ISSUE THREAD

**Issue by yakutovicha** [empa-scientific-it/python-tutorial#1]
## Main topics

- [x] #3
- [x] #7
- [x] #5
- [x] #4
- [x] #6
- [x] #8
- [x] #11
- [x] #10
- [x] #12

**Comment by baffelli** [comment]
Here are some topics I think could be useful for most people:

# Advanced Topics
- Type system
- Data modelling with types and Pydantic
- Functional programming (using iterators, compherensions, etc)
- Writing command-line tools
- 
# Basic topics
- Input and output (using context managers, etc)
- List, tuples, iteration
- Function definition and call syntax
- Control flow (Including execption handling?)
- Object oriented programming (methods, attributes, classes). Although this does not have as much use for the end user of python
- 
I know these are rather advanced topics, but these are the main things I use python for at the moment.

**Comment by edoardob90** [comment]
I split my ideas between "basics" and "advanced", but both concern the fundamentals of the language. I didn't come up with ideas to showcase external packages like numpy, scipy, etc.

## Basics

- Variable types
- Loops and control flow
- Functions
    - Parameters
    - Functions are objects
    - Side effects
    - Scope
    - Partials
- Built-in data structures
    - Tuples, lists, dictionaries, and sets
    - Common ops: nesting, copying, sorting
    - Comprehensions with iterables
    - Some functional programming: `itertools` and `functools`
    - Which data structure to pick and when
- File I/O
    - `pathlib` and the file system
    - Common operations
    - Reading and writing files
    - Handling CSV data (and the like)

## Advanced

- Creating and using modules and packages
- Functions in-depth
    - Iterables and arguments unpacking 
    - Functions as first-class objects
    - Lambdas, closures, and decorators
- Basics of OOP
    - Classes and objects
    - Python data model: "special" methods
    - Encapsulation and inheritance

I imagined that each of the main topics should wrap up with some hands-on or exercises, ideally of increasing difficulty. How many? 2 or 3, if we have more, I suggest to leave them in the repo for anybody who wants to dig deeper.

**Comment by yakutovicha** [comment]
One more topic we should probably add is testing in general and [Pytest](https://docs.pytest.org/) in particular.

**Comment by yakutovicha** [comment]
Another topic is about writing documentation and [readthedocs](https://readthedocs.org/).

**Comment by edoardob90** [comment]
Testing with Pytest is pertinent, writing docs slightly less. It's obviously important, but it deviates a bit from the overall purpose.

**Comment by baffelli** [comment]
Even testing is a rather advanced topic, I am not sure how many users are at a level of knowledge where they would benefit from testing.

**Comment by yakutovicha** [comment]
Good practices can be addressed as a separate topic:
- Python zen
- Separation of concerns
- Pythonic writing
- Duck typing.

**Comment by yakutovicha** [comment]
Isolated environments like pipenv or conda.

**Comment by yakutovicha** [comment]
Continuous integration.
