### ISSUE TITLE
Multithreading in Python

### ISSUE THREAD

**Issue by yakutovicha** [empa-scientific-it/python-tutorial#10]
## Basics
- What's Python Global Interpreter Lock

## Advanced

- Multithreading vs multiprocessing
- Process pool and thread pool executor
 - Python can only run I/O bound threads concurrently, CPU bound work is blocking (GIL)
- Alternatives to Multithreading:  
  - Asyncio
  - Coroutines
- Synchronisation primitives:
  - Channels
  - Locks
  - Mutexes

**Comment by baffelli** [comment]
This is only an advanced topic. We could cover

- Multithreading vs multiprocessing
- Processpool and thread pool executor
  - Python can only run I/O bound threads concurrently, CPU bound work is blocking (GIL)
- Alternatives to Multithreading: Asyncio, coroutines
- Synchronisation primitives:
  - Channels
  - Locks
  -
