### ISSUE TITLE
Use AST module to provide hints for exercises

### ISSUE THREAD

**Issue by baffelli** [empa-scientific-it/python-tutorial#101]
When we evaluate a cell, we could check for some of the most common mistakes that aren't syntax-related.
Example we saw during the course:

- Assigning a new constant value to the  the function input variables
- Printing as a last statement in the function body
- Missing return statement
- Returning a "print" statement 
- Returning None

**Comment by edoardob90** [comment]
I think this discussion can be merged with/continued in #68
