### ISSUE TITLE
Python packages, modules and releases

### ISSUE THREAD

**Issue by yakutovicha** [empa-scientific-it/python-tutorial#11]
## Basic

- **Python modules** to split a python program for easier maintenance and code reuse.
- Creating a module and importing its content (note on `import *`)
- Package - a collection of python modules.
- Intra-package references (`from ./.. import`)
- Making a python package installable (`pyproject.toml`)
- Releasing python package on PyPI.

## Advanced
- Executing modules as scripts (`if __name__ == "__main__"`)
- Importing `*` from a package (use `__all__`).
- Setting up Python package dependencies
- Dependencies and optional dependencies of a Python package
- Python management tools: [setuptools](https://github.com/pypa/setuptools), [flit](https://github.com/pypa/flit), [hatch](https://github.com/pypa/hatch), [poetry](https://github.com/python-poetry/poetry).

**Comment by edoardob90** [comment]
Mention to Release automation with [bumpver](https://github.com/mbarkhau/bumpver) and GitHub actions (mention)
