### ISSUE TITLE
Problem with tests in I/O module?

### ISSUE THREAD

**Issue by GCatarina** [empa-scientific-it/python-tutorial#120]
In the exercises of the I/O module, I am always getting some error message.
Example:

```py
%%ipytest

def solution_print_odd(n: int) -> None: 
    """
    Write your solution here
    """
    for i in range(n+1):
        if i%2==1:
            print(i)
    return None
```

gives the following error in line 94 of tutorial/tests/test_input_output.py:
SyntaxError: unexpected character after line continuation character

My folders are up to date.

**Comment by edoardob90** [comment]
Thanks! Yes, that's a bug in the test file. It's not related to the exercise you mentioned, but that syntax error is always triggered.
