### ISSUE TITLE
Show the proposed solutions to exercises

### ISSUE THREAD

**Issue by edoardob90** [empa-scientific-it/python-tutorial#125]
- Add a "Show solution" button (via `ipywidgets`)
- Parse the corresponding test file and extract the `def reference_solution_XXX()` (with the `ast` module)
- Render with an HTML display block. It would be **great** to have syntax highlighting (with [pygments](https://pygments.org/docs/quickstart/), for example)

## TBD
- How to handle external packages that the solution might use?
- What about utility functions defined elsewhere?

**Comment by baffelli** [comment]
Utiliti functions defined elsewhere can be retreived using the AST module. It isn't going to be super easy, but it's a fun challenge.
