### ISSUE TITLE
Enforce minimum Python version

### ISSUE THREAD

**Issue by edoardob90** [empa-scientific-it/python-tutorial#148]
I think we should strive to support Python 3 without enforcing a particular version. I mean, maybe 3.3 is a bit old, but 3.9 should work almost as good as 3.12. It isn't because we used the `match` construct in the test helpers. I think it should be an easy fix.

https://github.com/empa-scientific-it/python-tutorial/blob/6fc3d8bcf988a681c48f3e3ea70d1044cfc87e81/tutorial/tests/testsuite_helpers.py#L324-L330

I tried to run our tutorial on Piz Daint and they are "stuck" with Python 3.9, at least if you follow the docs on creating custom environments for Jupyter.

**Comment by edoardob90** [comment]
I think we agreed on supporting from Python **3.9** onward. We should then adapt the `match` construct in `testsuite_helpers.py`

**Comment by yakutovicha** [comment]
Maybe 3.10 then.

**Comment by despadam** [comment]
Covered in `binder/environment.yml`
