### ISSUE TITLE
Allow the function under test to be asynchronous

### ISSUE THREAD

**Issue by baffelli** [empa-scientific-it/python-tutorial#159]
A simple change is needed in `testsuite.py`:
```python
for name, function in self.shell.user_ns.items():
    if name in functions_names and callable(function) or inspect.iscoroutinefunction(function):
        functions_to_run[name.removeprefix("solution_")] = function
```

**Comment by edoardob90** [comment]
I think you need a parenthesis otherwise it will short-circuit if `callable(function) == False`

**Comment by baffelli** [comment]
Thank you @edoardob90 .  I still ran into problems: to be able to run async test I need to run the pytest tests in another process. This means I need a queue to collect the test output. It will require a bit of work to get it to work...

**Comment by edoardob90** [comment]
Ideas:
- Find when pytest needs to run in a separate thread
- Don't run `pytest.main()` directly but from a wrapper function that handles the threading

Hints from [this package](https://github.com/chmp/ipytest/tree/main):

```python
def run_func_in_thread(func, *args, **kwargs):
    res = None

    def _thread():
        nonlocal res
        res = func(*args, **kwargs)

    t = threading.Thread(target=_thread)
    t.start()
    t.join()

    return res
```

Here `func` is essentially the following function:

```python
def _run_impl(*args, module, plugins, addopts, defopts, display_columns):
    with _prepared_env(module, display_columns=display_columns) as filename:
        full_args = _build_full_args(args, filename, addopts=addopts, defopts=defopts)
        return pytest.main(full_args, plugins=[*plugins, FixProgramNamePlugin()])
```
