### ISSUE TITLE
Errors found in `manage_python_project.ipynb` notebook

### ISSUE THREAD

**Issue by yakutovicha** [empa-scientific-it/python-tutorial#167]
Please report here any errors or  suggestions for the [`manage_python_project.ipynb`](https://github.com/empa-scientific-it/python-tutorial/blob/main/manage_python_project.ipynb).

**Comment by despadam** [comment]
Typo in **Preparatory exercise**:
- **other** yours or the one you have forked --> should be 'either'

**Comment by fabioacl** [comment]
In the line `bumpver update --minor --dry-run` it should be `--dry` and not `--dry-run`

**Comment by fabioacl** [comment]
In the Testing section, add `job` before `tests`.

**Comment by anates** [comment]
Executing `bumpver update --minor --dry-run` as proposed fails, as there is no entry for `__version__` in `__init__.py` in `mypackage`. Manually adding this entry resolves the issue.

**Comment by edoardob90** [comment]
There seems to be an issue on Windows and the `yamlfmt` hook. I don't know if it's reproducible every time, but it seems to be a bug in the hook script itself. Check out: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt/issues/25

**Comment by yakutovicha** [comment]
The exercise on releasing automation needs to be revised. It is not clear to people what is `test.pypi.og` and how to release things there. Maybe, it is enough to release only on GitHub.

**Comment by yakutovicha** [comment]
> Last entry in the notebook for publishing a new release, currently reading
> 
> ```
> - uses: softprops/action-gh-release@v0.1.14
>    name: Create release
> ```
> 
> should be
> 
> ```
>     - name: Create release
>       uses: softprops/action-gh-release@v0.1.14  
> ```
> 
> afaik. Is that correct?

It should not matter, as after reading it becomes a dictionary:
```python
{
    "name": "Create release",
    "uses": "softprops/action-gh-release@v0.1.14",
}
```

but I agree this way is more consistent. I will fix it.

**Comment by yakutovicha** [comment]
> Executing `bumpver update --minor --dry-run` as proposed fails, as there is no entry for `__version__` in `__init__.py` in `mypackage`. Manually adding this entry resolves the issue.

This I will do directly in the `mypackage` repo.
