### ISSUE TITLE
Interest for solution files for `poetry` in addition to `pip`?

### ISSUE THREAD

**Issue by anates** [empa-scientific-it/python-tutorial#169]
Typically, for my projects I am using `poetry` instead of `pip` or `pipenv`. This requires some changes to config-/toml-files. Would it be relevant for this tutorial to have alternative solutions when using `poetry` instead of `pip`? If yes, I can try to clean up my files and provide them in a pull request.

**Comment by yakutovicha** [comment]
Add a paragraph on the existing package managers and links to them
