### ISSUE TITLE
Reorganise "Modules and Packages" and "Manage Python project"

### ISSUE THREAD

**Issue by yakutovicha** [empa-scientific-it/python-tutorial#196]

**Comment by edoardob90** [comment]
Partly related to #205

**Comment by despadam** [comment]
Hi @yakutovicha 👋 

I went through the `Modules and Packages` notebook and in the end I don't think it is too much for the beginner's course, considering it is the last chapter that we will cover. By then they should feel more comfortable with Python and a chapter like this should not scare them away. It is useful knowledge, so I suggest we keep the content as is and let them see how far they can get. Perhaps the last part about GitHub will be a bit tricky if they haven't used it before, but I still think it's a good exercise. 

My only suggestion would be to add a couple of extra sentences, explaining a bit better what a `.toml` file is, in the `Make the package installable` section.
