### ISSUE TITLE
Added branch for testing of solutions

### ISSUE THREAD

**Issue by baffelli** [empa-scientific-it/python-tutorial#21]
As discussed today with @edoardob90. We are trying to get test suites to run automatically with some cell magic.
Please have a look at the branch testsuite. Unfortunately I am not able to create a merge request because I accidentally pushed these changes to the main branch...let me know if you have a way to fix that other than  my kludges.

**Comment by edoardob90** [comment]
Okay, I changed the protection rules which should now include admins. It should be impossible to push directly to `main`. However, that option disabled the possibility of bypassing the checks when a pull request is opened and not yet ready to merge.

Another idea I found to completely safeguard the `main`, is to add the following git hook locally at `.git/hooks/pre-commit`:

```
#!/bin/sh

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  echo "main branch commit is blocked"
  exit 1
fi
```
