### ISSUE TITLE
Errors found in the `basic_datatypes` notebook

### ISSUE THREAD

**Issue by despadam** [empa-scientific-it/python-tutorial#232]
- [x] Add `import math` in `solution_circle_area()` in basic_datatypes and explain that `pi` is defined there
- [x] It is not clear that quadratic equation expects two results
- [x] `solution_number_is_lower_than_0_or_greater_than_100` in the test we check for `>=`
- [x] in comparison operators, explain the difference of `==` and `isequal` with the float number problem and how is it repsresented in bits

**Comment by yakutovicha** [comment]
in the `def solution_number_is_even(number: float) -> bool:` the input types do not match. It should be `number:int`

**Comment by baffelli** [comment]
https://docs.python.org/3/library/decimal.html

**Comment by baffelli** [comment]
In the exercise `solution_return_first_and_last_element_from_list`, the annotated return type is `list[float]` however the solution checks for a `tuple[float, float]`. We should make this consistent

**Comment by baffelli** [comment]
`popitem` does not remove an arbitrary element but the last element inserted into a dict.

**Comment by yakutovicha** [comment]
For the record: it takes roughly 3 hours to finish the basic datatypes section, so we might want to give students a bit more time for the next tutorial.

**Comment by despadam** [comment]
From #233: In the basic datatypes notebook, trying to convert a complex number to float raises a TypeError as expected. However, it doesn't print the error to the console unless it is surrounded by a try...except statement.
