### ISSUE TITLE
Errors found in the `control_flow` notebook

### ISSUE THREAD

**Issue by despadam** [empa-scientific-it/python-tutorial#234]
- [ ] Add more examples for one-line syntax.
- [x] Provide multiple solutions: from a simpler one to a more advanced one.
- [x] Add a section explaining the complexity that a nested loop adds to the code and how to avoid this.
- [x] Add better explanation and more examples for `continue` and `break` statements.
- [x] In exercise `find a pair of numbers`:
    - [x] specify that we are looking for the first pair encountered,
    - [x] specify that the two numbers should not be the same,
    - [x] show how to solve this with both a nested and a single loop.

**Comment by edoardob90** [comment]
Fix this test with a simpler `dict.fromkeys()`:

https://github.com/empa-scientific-it/python-tutorial/blob/b2eca0ff5f3597e64f7ff2dbaf0bf8016fa70576/tutorial/tests/test_control_flow.py#L197
