### ISSUE TITLE
Errors found in the `input_output` notebook

### ISSUE THREAD

**Issue by despadam** [empa-scientific-it/python-tutorial#236]
- [x] Add a line to execute `solution_print_salutation()`, so they can see the output, since this one cannot be tested normally

**Comment by yakutovicha** [comment]
The exercise `solution_find_all_files` has issues:
* We provide the following solution `list(f.parent.iterdir())` but it should not have `parent` in it.
* The path argument in our solution should be `current_path` instead of `f` for consistency.

**Comment by despadam** [comment]
In `writing to a file` section:
- we have 3 exercises but they are enumerated wrongly (instead of 1,2,3 we have 1,2,1)
- `solution_read_file` should be removed from this section. It is a duplicate

**Comment by despadam** [comment]
In `reference_read_write_file` we are using `line.strip()` and `len(line)` for a string. However we haven't introduced any of these two in the section for strings in `basic_datatypes`
