### ISSUE TITLE
Errors found in the `modules and packages` notebook

### ISSUE THREAD

**Issue by despadam** [empa-scientific-it/python-tutorial#241]

**Comment by despadam** [comment]
In `exercise on installing the package` specify that they need to be in the parent `mypackage` directory. They were already there and since the exercise asks them to execute `cd mypackage` then they end up in the `mypackage` subdirectory where the `.toml` file does not exist.

**Comment by yakutovicha** [comment]
> (not sure about this one) In `Exercise on importing from parent modules` should they import from `mypackage` or `mypackage,geometry`?

Importing from `mypackage` is the way to go, because `mypackage.__init__.py` already imports the `geometry` module.
