### ISSUE TITLE
Ipynbname does not work locally

### ISSUE THREAD

**Issue by baffelli** [empa-scientific-it/python-tutorial#30]
Instead of finding the name of the notebook, `ipynbname.name()` raises a `FileNotFoundError` when working with a local ipython kernel in visual studio code. I suggest using the old way of loading tests where we manually specified the module where they resided. I anyway would prefer a mode explicit solution.

**Comment by edoardob90** [comment]
Specifically: it doesn't work within VS Code or PyCharm. I propose two solutions to consider:

### Add an exception to handle VS Code

When running IPython inside VS Code, a global variable `__vsc_ipynb_file__` points to the basename of current notebook. We can infer from that the notebook name. Downside: works **only** with VS Code. Pro: no changes to the syntax of calling the testsuite.


### Add an argument to the cell magic

The name of the module. It should be **only** the name, for example: `%%ipytest functional_programming` will run test from the `tests/test_functional_programming.py` file. The rest should stay the same (i.e., test functions must have `solution_` prepended). Downside: we need an argument. Pro: robust, we're effectively hard-coding the name of the test module.

What are your thoughts, @yakutovicha ?
