### ISSUE TITLE
Input and output

### ISSUE THREAD

**Issue by yakutovicha** [empa-scientific-it/python-tutorial#4]
## Basic
- Reading files:
  - open, close
  - binary vs text mode (encoding)
  - read, append, overwrite modes
  - writing and reading with iteration or with `read_lines`/`write_lines`
- Reading and writing `csv` with the built-in csv module
- Managing Paths with `pathlib`
  - creating paths
  - resolving paths
  - path manipulation (suffix, appending, renaming, globbing, ...)

## Advanced
- Streams with the `io` module
- Implementing file-like behaviour on other objects (adding `open/close` methods to other resources)
- Context managers for resource management (`with` keyword)
  - understanding context managers
  - implementing context managers to handle custom resources
- Databases
  - local databases with `sqlite3` module
  - database querying with `pandas` (_maybe_, it's not part of Python stdlib)

**Comment by baffelli** [comment]
# Basic
- reading files:
  - open, close
  - binary vs text mode
  - writing and reading with iteration or with write_lines
- reading and writing csv with the built-in csv module
- paths with pathlib
  -  creating paths
  -  resolving paths
  - path mainpulation (suffix, appending, ...)
# Advanced
- streams with io module
- context managers for resource management
  - understanding context managers
  - implementing context managers to handle custom resources
- databases:
  -  local databases with sqlite3 module
  - database querying with pandas
