### ISSUE TITLE
Rephrase exercise 1 in control flow

### ISSUE THREAD

**Issue by baffelli** [empa-scientific-it/python-tutorial#48]
The problems with find the pair (Exercise 2) have a misleading return type. Shall we return a list or just a number?
It seems we need to return the product of the triple, but it is not so clear from the question.

**Comment by edoardob90** [comment]
I'm closing this as I'll be adding this adjustment in PR #52

**Comment by yakutovicha** [comment]
IMO, a better approach is to mention that PR #52 will fix this one too.
