### ISSUE TITLE
Functions

### ISSUE THREAD

**Issue by yakutovicha** [empa-scientific-it/python-tutorial#5]
## Basics
- Writing a function: parameters, body, `return ` statement
- Annotations and docs
- Parameters vs Arguments
- Position and keyword arguments
- How Python executes a function (definition vs execution)
- Scope (`global` and `local`)

## Advanced
- Functions with mutable arguments and default values
- Functions are objects
   - Functions can be stored in data structures
   - Functions can be passed to other functions
   - Functions can be nested
   - Functions can capture the local state (closures)
   - Functions can return other functions (decorators)
- Functions and iterables: unpacking, the `*` and `**` operators, `*args` and `**kwargs`
- Lambda expressions and their purpose/limitations
- Pure vs impure function (with side-effects), best practices with separating the two kinds

**Comment by edoardob90** [comment]
## Basics
- Writing a function: parameters, body, `return ` statement
- Annotations and docs
- Parameters vs Arguments
- How Python executes a function
- Scope (`global` and `local`)

## Advanced
- Functions with mutable arguments
- Functions are objects
- Functions and iterables: unpacking, the `*` and `**` operators, `*args` and `**kwargs`
