### ISSUE TITLE
Provide small exercises in the middle of notebooks

### ISSUE THREAD

**Issue by yakutovicha** [empa-scientific-it/python-tutorial#57]
Currently, in many notebooks, the exercises are placed at the end, and they are often quite hard.

It would make more sense to do more "intermediate" exercises after we cover each topic to better prepare the students for the hard ones.

This will also suggest the students go through each topic more thoroughly.

Here is the list of notebooks that need to be adapted:

- [x] #118
- [x] #215
- [x] #216
- [x] #217
- [x] #117

**Comment by edoardob90** [comment]
I guess that also "Object-oriented programming" can benefit

**Comment by edoardob90** [comment]
Linked to #207
