### ISSUE TITLE
Readme: update section on "run the tutorial on your computer"

### ISSUE THREAD

**Issue by yakutovicha** [empa-scientific-it/python-tutorial#58]
We should add a few lines explaining how to download the archive with the tutorial

**Comment by edoardob90** [comment]
An additional adjustment: since `environment.yml` has to be moved to the `binder/` folder, we need to update the `conda` command to create the environment. Or we can copy the environment file in the root folder as well.

**Comment by edoardob90** [comment]
Also related to #80

**Comment by edoardob90** [comment]
Related to #80
