### ISSUE TITLE
Functional programming

### ISSUE THREAD

**Issue by yakutovicha** [empa-scientific-it/python-tutorial#6]
## Basic
- Iteration and filtering using comprehensions
- Reduction (useful for "sliding window" operations)
- Combining iterators with [`itertools`](https://docs.python.org/3/library/itertools.html?highlight=itertools):
  - `tee`
  - `zip`
  - `map` & `filter` (lazy methods)
  - generalized `zip`
  - transposing

## Advanced
- Lazy computation and iteration with generators (`yield`)
- `itertools`:
   - infinite iterations
   - `groupby`
- `functools`:
  - caching
  - partial application (currying, `partial` objects)
  - single dispatch

**Comment by baffelli** [comment]
# Basic
- iteration and filtering using comprehensions
- reduction (useful for "sliding window" operations)
- combining iterators with itertools

# Advanced
- Lazy computation and iteration with generators
- itertools:
  - infinite iterations
  - groupby
  
- functools:
 - caching
 - partial application
 - single dispatch
