### ISSUE TITLE
Topics of the advanced tutorial

### ISSUE THREAD

**Issue by yakutovicha** [empa-scientific-it/python-tutorial#66]
> **Important**
> We agreed on the following *definition* of "advanced": **something that requires the understanding of and build on what we said in the Intro Tutorial**. We are assuming that all the participants are comfortable with every Intro topic.

### Advanced topics

- [x] #12
- [x] #124
- [x] #121
- [x] #122
- [x] #10
- [x] #123

### Python Libraries

- [x] #144
- [x] #147
- [x] #143
- [ ] #146
- [x] #142
- [x] #145
- [ ] sympy
- [ ] ipywidgets
- [ ] traitlets
- [ ] numba
- [ ] asyncio
- [ ] ase
- [ ] pymatgen
- [ ] ~~toml/yaml~~
- [ ] pydantic
- [ ] ~~subprocess~~

**Comment by edoardob90** [comment]
I'm not sure if TOML & YAML _deserve_ an entire morning. Definitely we can bundle them together.

**Comment by yakutovicha** [comment]
And with this last library, we can officially close the issue. Congrats @baffelli, @despadam, @edoardob90, @fabioacl, @ramador09 

I think we did a great job  🎉
