### ISSUE TITLE
Control flow

### ISSUE THREAD

**Issue by yakutovicha** [empa-scientific-it/python-tutorial#7]
## Basics
- Looping constructs and iterables
- Altering and breaking out of loops: `continue`, `break`
- `if-else` construct and problems with nesting too many branches
- The `else` clause for loops

## Advanced
- The [`match` construct](https://peps.python.org/pep-0636/) (Python 3.10.x) to avoid nesting
- Pros & cons of looping (when it's better to use functional programming methods)
- Recursion and its limits
- The built-in `Exception` class
- Built-in exceptions: `TypeError`, `NameError`, `KeyError`, `ZeroDivisionError`, `OverflowError`
- The `try-except-finally` construct
- How to handle exceptions to have a stack trace useful for debugging

**Comment by edoardob90** [comment]
## Basics
- Looping constructs and iterables
- Altering and breaking out of loops: `continue`, `break`
- `if-else` construct and problems with nesting too many branches
- The `else` clause for loops

## Advanced
- The built-in `Exception` class
- Built-in exceptions
- The `try-except-finally` construct
- How to handle exceptions to have a stack trace useful for debugging
