### ISSUE TITLE
Functions Quiz Q2: Expected Answer Inconsistent with Tutorial

### ISSUE THREAD

**Issue by zaunak** [empa-scientific-it/python-tutorial#74]
The tutorial states about type hints:

> Python doesn't require you to explicitly declare a variable's type. However, when defining functions, you can add type hints in the function's signature.
>
> **Type hints improve code readability** and can help catch potential type-related bugs early during development.
>
>The Python interpreter does not enforce type hints and will not check them during runtime. **Type hints are primarily intended for improving code readability**, serving as documentation for developers, and making IDEs much more helpful when writing code. 

However, the question "What is the purpose of type hints in Python function definitions?" is not correctly answered, when the answer "To make the code more readable" is selected.

**Comment by edoardob90** [comment]
Thanks @zaunak! The options to that answer were indeed not clear. I rewrote them and provided the correct solution.
