### ISSUE TITLE
Object Oriented Programming

### ISSUE THREAD

**Issue by yakutovicha** [empa-scientific-it/python-tutorial#8]
## Basics
- Creating a `class`: a blueprint for objects
- Methods and attributes
- Objects instantiation
- Special methods and the Python Data Model (a tour or `__dunder__` methods)
- Duck-typing

## Advanced
- The `@property` function to define attributes (setters and getters)
- About private attributes: comparison with OOP languages like C++/Java
- Inheritance
- Write better classes with `dataclasses` and `attrs`

**Comment by edoardob90** [comment]
## Basics
- Creating a `class`: a blueprint for objects
- Use classes to create new objects
- Objects instantiation
- Special methods and the Python Data Model

## Advanced
- The `property` function to define attributes
- About private attributes: comparison with OOP languages like C++/Java
- Inheritance
- Write better classes with `dataclasses` and `attrs`
